apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ppDBld8ZMcoIQhnhgZVLFQj3Z2QH18+qBOTRMzU/iSgNCoIWVAgsuA==,iv:aVYPAbktOKrZRdCE3SE4zXaZFpPl4+tIhuApDzoM6lI=,tag:oIU8hx5WrshxjkQvN40jmw==,type:str]
sops:
  age:
    - recipient: age1k77zxd34j3sl930pyrscjchegnugy6pgea6vpscwn3wt8kkf7u2sm6vykc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFd1pjSWllS2Z2V0Q0a1Ru
        Qzg0YVdXV1Q5dHQ5REdvSU5MNmRqZXRQaXlRCmc2N3BVVnpzUW9RQytwY3FEbEF6
        Z09qZlp0Yncya0xNc1FMT3pnUHFBR1UKLS0tIEZpSE1UbUVOUmpYaGNyblprR3kz
        ZDZhL2U3aFF1RjdDTURCRU53KytGaVEKhRT4XeKFuHJBXknkKt7vVodnd7VhDHTT
        HcgBpCxSjvVsE5/B+6cmu6WDRzpWrIrZXc0dXNbhplLEx5BGb4XuKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T14:14:50Z"
  mac: ENC[AES256_GCM,data:kCGmMoC95AiXcuGx6qog0HfylT8d2e6hDWyR+hpwfVpcrVMnSHWj5HIQm0swjSvH+PEEV7Uz8pgIVZkXSAIM2s4AnxcOVVAd0i9rRvfBrfzDRfRQrrkIehqaPM1thcYUR0Xyhg5W0KFr3QAsCaZz9bGqE6h6Mbd/w0GGnKp2rDs=,iv:T03g14bEhdxT4CxSrk2uzgOWotq1lMaQmPkkb0ZP6Xo=,tag:5LvTz3a/Lee1wsIJ63E4wg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
