apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Hmm1hrf5+6j76jYofOlTtXzN9PNm4Y4MdUkybfUi4W67FBePPJhAFQ==,iv:odHMpPH/Cq9K148hQn/JdHWAxqNIQY4KrG44ZRRbd6A=,tag:rMwQZ20ozSk241YRhTCo+w==,type:str]
sops:
  age:
    - recipient: age1k77zxd34j3sl930pyrscjchegnugy6pgea6vpscwn3wt8kkf7u2sm6vykc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWHVXQnJlZ1RUZXQrVUlG
        T3A2ZDhSYmNJS1VpSGoweDJmRWxxOHFoU3lFCjRQZld0TURXcGtNWHo5WFJDQmY2
        eUNoZkVkbjhuRmRtUTlEcTBCWW9MNDgKLS0tIDhrank1bk42NmtzZzJFSGpxRFBl
        OFl4b2xWOTQyTUhGN1BNcE9tSFhZN1EK/pITPeGrU0IKP5VcrNCLPVk7024eMB3p
        t8b1et8zeplHIOEFGPeVSrRfLWj7pV/C/p3V/unu5x+dlvs1x8z2CA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T18:36:08Z"
  mac: ENC[AES256_GCM,data:K5XypcjDL+iY2cqjxbXokeVf/uw1kLiKgC3X4eyRSlRYZwtCRxct/fUJ85clF/A5CdZKKNmJGtTT8MHhokE5eHomg8PVUvspS0rXX1zWYN5R3I6HlmNl6C1eCy+t/gfFzUHFzmXNdimWUTMd51wbhOoGJ5wmLQ5be0hPLPl1WEA=,iv:SFuUUr7gioBpcvvfhYtLLQ0dffHkm2srh64KpjyRoAU=,tag:Q3VaLD0nP1qhyBFouUPGiw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
