apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:OlkBsMm72t1NY49oWyDHzug6VF9imAJAcc9LdecClqhJ/tgFtZ1qOg==,iv:bEzFkut38XNNpAdlxByWZ5U3aMItzQyL1J2vFmbPNpw=,tag:T1HJXsw+IuKibydH2//YxA==,type:str]
sops:
  age:
    - recipient: age1k77zxd34j3sl930pyrscjchegnugy6pgea6vpscwn3wt8kkf7u2sm6vykc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRG1uV1RaVlF3NWYyc1Z4
        QWI5N1R6UEoza3JqWHJ5em5DaVVIajNDQVFjCngvaWNrUmdGemoxSDNtVHhEVFpP
        N0Ivc0VOb3FzTkxlblRiL0IzcWo4Z00KLS0tIDlMaU83UUxpMXkrcGJUWnJlNWxi
        YUo4WFA0T1FVOFpaNmhpbks3YWpsVjgKUJ80eOisx1cdfKlp14Omxv6EvPxDVL9d
        tJMax696kTF0hhAr/xwwsAlhENcq68owrCqvQPGrZbfUfxhpjfzSMg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T17:50:31Z"
  mac: ENC[AES256_GCM,data:vSZqwdw9YAPJxEWV1qKQKJvSXg/XU1KJgbhaDlXSP53kXeBPNOqY+kQlp9ETSZm4UrNaJ/fiMCrphs+uIK1K3LdsHmTN8EVzQbjRY8MWkQyTm2vcH1wKIh7E/6Zff1l1OmQpvuAIVmkzvz/3PmTAxhdoEfRrGWQOfIhNOTZmaEU=,iv:yyt3JZA9oR/2wC8/q5feJDdj0NwvkFVHGuLojVjqETQ=,tag:3BJhJ+QYrKkXJjtycrKR/Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
