apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:iXpR2P4jYOETqBh8kJJ8hQRjWmQwOCNBhlzerGlyiADWmcAAq3DgPA==,iv:Ywm/kJosCxMuOkE9WkZDYtE8wpky1GmHlrSt/i3egok=,tag:kZ1KGjSxvHWS1nkVxo2ShA==,type:str]
sops:
  age:
    - recipient: age1k77zxd34j3sl930pyrscjchegnugy6pgea6vpscwn3wt8kkf7u2sm6vykc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TFJYbVJRbjJOLzlsaU5V
        ZStEOE1tY0N2M0Q3MkJxYk5PVjY5RlRTWHlJCmpleURuSlB0YjlhdWtRY0JlKzhr
        cHlHQ29sNGJSRWpJVXBtV0pCOWxIR1kKLS0tICtmWXE1ZVhiSm1ZNGZxQ01FY2JT
        V05LRDBUWjNqNlJpbWQwemxoTGkwWUkK2pZ51vaYQSRiUbYj59zWHhqG+VVjTSok
        UlJ5gQ+2436FL7Lx33D4mojTI618aXDrTmKPyUdGMCc2dPDitWI+RA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T12:56:31Z"
  mac: ENC[AES256_GCM,data:7shc1oC43D1ywNPxM7A7LJq8msvyz1vMmxcUxE7sFOz0RhOTv0A7D99VqK0xIyOG8vnZRfiOttaTQhFm2cjjJyjW4BdMraYzFmtC4vj+IbhSab4Gda4ia1BCIr9MgAyKgr+P0CxN+wIy/WRbbHP7yiQwU1mSNLZp2o5Cv2CcN6Y=,iv:PZv6KLlSRhCBejk1fckD8okq/7Mh91277888endNxvY=,tag:w0ULFCx7+PeD72ZleWCn9A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
