# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: observability
stringData:
  admin-user: ENC[AES256_GCM,data:V4GPdOo=,iv:TbNZidHMSDxmWqYckB8pLpzUOIbVx1o3Ax9QkUPG2ks=,tag:7mFpgUtAvwNazgrO5Q5TEg==,type:str]
  admin-password: ENC[AES256_GCM,data:f5Q3E/rcIYp1fR07sK2TFw==,iv:/Ag1uhsysAi5djeDP7ncbLUm0rvmsmzeDMJH+IhKAW4=,tag:erkDrxjFb7bnn2uWj7AEFw==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWk9JNnhRR2srOFA3Rm1M
        SHhlUnB4S0FhaGhlVWFqai9vbU8vZ0R2S21VClY2bmdOeVlIVk9ZdXVMMGFPY1Ux
        ME54NUZnWlJCV084Ti9XSUVPQjBRMkkKLS0tIDdVQkM3QnZhbWhYTGRkZjBPYUQy
        OFpjZDIyMTVCUG01dDJ0NGhyMG96OFkKN3SMnMeFkHsW2cr7kf1s6DJLJuxwMbf2
        0k/0VwcoGB5CP3416aBAJ2BYi4upWMIUx1AhH2xnxO+kLw4p/xCAsA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-10T21:31:06Z"
  mac: ENC[AES256_GCM,data:g4XBIKXlEuvKeVoscRkWYrUsW/Gfc5IvPON0AwvE5LquT4TQcLwRz5AuVJc4bF9CWmiCOhHnckohL9I0ki0LwhzAkLc1qCfxT6hcU4nNumG1cPq+xCU1FS9Zvpb5r6B3PXKL5bMx8481xrrNkf3T7GGt8HTPa5WMoGFpyQyhRo0=,iv:J7vol28zBXNBHrtxYorZxuCAO5tpdUjLfTv9tQeXuRo=,tag:wNUXPz5QqZJFkZV4CfmQXQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
