apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:BU3zuJZOS7JK,iv:ncVFdqGUAbP3iO4CGSzk0w77YZuSUM59xa1vILriOVc=,tag:55UkUaOijv7SluRj1rRKWA==,type:str]
sops:
  age:
    - recipient: age1k77zxd34j3sl930pyrscjchegnugy6pgea6vpscwn3wt8kkf7u2sm6vykc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnY1dvbytUbGlYZk1YTGY1
        VlJRZENYSVJCQkZucEh3S2dIa2hXY1ZGU0VNCk1tT1JXVS8vZ0xnNFpieDNQQUJM
        ZmE0a2podnBuT2t5aU5rcE1yWUxoN0EKLS0tIDJZT0JGdjNMZ24vRDlRYjRGUG9i
        WG9kT1EwS3pzbVZWZUwwdzEvUWhaSXMKAufc5cfQ/h8qf5am+KtBr/Wl0fkdjddi
        WJGZJb+JheNIFCo+xt+yXVuTHRHuFj8250Hc+4IElp0fTm0jEy/AWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T17:50:31Z"
  mac: ENC[AES256_GCM,data:WnCKiEEXTAeHCyqD7SLMAhv9W7MsNQeb7esvx2jgqbXJBfhFzTR2rDlbi2A6ms1etvUmzo/uGOvQmoIm1LxrXM0trSNfpS6c5opVQchFWHPZzBfwPi4qP8Z8H83FP99tN7cj9LSJxhdXF13tuV2zqFJEi4TrwGfa314cwaXpvsU=,iv:5Nrp6EULuJggFEHzVbWHtBHgjb5p9sSRH8NOtiLXfrI=,tag:B5XTgzM2JFOa/5DeAfC4yQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
