apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:W7LMeBPsP8nP,iv:rWPznJnfuEH/QagOlvUqOrmXKXsSpprTAmJ248iEnN0=,tag:9hWyLhOC9jBjEP0BiBl5Iw==,type:str]
sops:
  age:
    - recipient: age1k77zxd34j3sl930pyrscjchegnugy6pgea6vpscwn3wt8kkf7u2sm6vykc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaE1rS29RSDBXYXdpN2pB
        UkRzakJvaDNmdC9uakZXWHRDazNhaWZ2b1ZzClY3d0lGWEh4MElqNVFiaUlmem1Q
        Sm5YTFE3WHd5aUVQc3RqV1pYalVKQlEKLS0tIDU3a3JsVjdhaHdMTklCM0tJV0J1
        RlVnVzd0NzlKVlk3c1ZqT0RXb2syUGsKJeBQhQx3M/SN6PhAzT6Dwlr76vCBKVa+
        0VnFV0eUc8e9gY40z4IAB2itU1oGgYd4GcmT64IwVYfQ7LthgfTqGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T18:36:08Z"
  mac: ENC[AES256_GCM,data:SpeB3KmYiebVrfUwce5PYgXSnzrnSskubCsY6mL/uyuinHKYc3DMnK1sjWhAowTQNaL6n0iq7LVI4ENw4RLUgURqDOf+SlJb6Cv/Ny8CQY9DqUiXqV2U3qBHRf94ABFULMg97Ay3EKl0Q392k6gU42QLNw0vdsrXtOOwlvcW7q4=,iv:3LxlNdXeFuwcZJ08CdKvKCV8MOEiiordxZdX9KZDO0g=,tag:AypWUi+7m37I9230MxQ4pQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
