apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:5+WUN2X1AHPz,iv:9RuEZ2duPBOuKnyxcRwvvGQUTWoWjyvE0VfGvI7LphU=,tag:25qzYhTC4ioAOJqPYksDiQ==,type:str]
sops:
  age:
    - recipient: age1k77zxd34j3sl930pyrscjchegnugy6pgea6vpscwn3wt8kkf7u2sm6vykc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWkI5OE5OcHpYc0RNaHpM
        QisxQTR2akNvb0lVVmUyU3hDV0ZnQUNDY1c4CkNEQkw5S1V5cHA0RVBKRkhKT2V2
        VzVlM3k2WnRMN2VrQlRPTE1vem5UT3MKLS0tIGhZdjdHSENGaGZtdXdHZzZIOUpx
        Z1RRbE9LNW8xUlRsZUlqaHB2UkZRaEEKIkNEtiU35+sTRhYCbc9sB44GjJZzkQdX
        hkfRQkA9/VFfWUyrbBj3ta25JsIK+iux7OfYZ/R2IyZNv88kmvtYag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T14:14:50Z"
  mac: ENC[AES256_GCM,data:ndktiHO7hZcXkPLc+VySxwFyeMYiC8XhLF+gc0u1kYozjca60yjSvRcrTIjxZbLwa6g70+KXxq4clsrOyDIjv3vM5fOBKESBIW44HmkwFIbmSUEIlQpgB/7cFn3xDElog3gWr84gCK4csikCY+8IAfzjvGjuuFUSKlUewvN2F5Y=,iv:BPCZdHHGyVBpGrfLRa7DmTtsqPNqeIcRJ3iKsLG7dyQ=,tag:atv5VPuVu7pG7r0V87aUmw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
