apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:t8pA0P69gw0o,iv:SZkmcbnQXouo7bGQWVw/kXn6p1B/2EDQ5CLwE/LrTdc=,tag:if/DfBE72IGYcjiZouCZrQ==,type:str]
sops:
  age:
    - recipient: age1k77zxd34j3sl930pyrscjchegnugy6pgea6vpscwn3wt8kkf7u2sm6vykc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NGk2a1YrV0tYMldha1BM
        dlZmbzhpaXFKUnFiWTZjWlBsM1Y1dHpxY1NNCmZUT0svdnhTWG53d1lLU2VXenM0
        SnE2RXZKY3FiNnM1N0VhZHZ1SSt0RzgKLS0tIFovWnU5dTJDeHRNVnBaNFZtWGpX
        WUZYYU5PNDJPRy9HcENnNVhubXEzRncKyZbruZa+ojpbLeQlVj+q40k8GCd93OZa
        rWTy1uvc3JGPAImxEDhaxplvjnC3GdIkjWtvefNmxvbsbKaw1Fiv7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T12:56:31Z"
  mac: ENC[AES256_GCM,data:1vHJcPGMF3lgpZZ0bsxE8mtCurBuXNgUKWExWLMLLKO0gZ57benX8u/QGYefpN9bklg1VXJcqe/M5x99v8ZhUu3Y9lKow+ihnfjVnNQfGDwwOR8Kl9j5Lpt8xM3aUMioL69Vfs7GCtcEJ2gZzERiX/8aHcOq9QnsRxPWQ7Te9dU=,iv:s5oEzcq0xZ5Ajvj4eEMPh3uGULGhIgmn/tLh/E9qf1o=,tag:fHNzIv0YUh8xvoOAlrjeNw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
