apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ""
sops:
  age:
    - recipient: age1k77zxd34j3sl930pyrscjchegnugy6pgea6vpscwn3wt8kkf7u2sm6vykc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaHJ3Unl1UGw1SHZMUE52
        dnRGVXF4WGVlZ2Q2djNPZXpiZFFyUkJKYkJZCmxlM0tCNzNtblVZWk55RWhnMzFX
        MHFQd0NlQjluZ0dXMHJ3RkFPK3k0WGcKLS0tIDRtSlJVU2Z3dS8rUEN2MHUvVG9r
        WE8wTlZoTTNmOGtqSnFwTjAwa1FiSXMKww2Cc+nCpGmSgaeUVH+rFxDA376YoP6z
        h97Q33ktIg4BJcYbYdPsGSsGHyUFaLx2OqQZIiMG0GZKmuxliA+U8g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T17:50:31Z"
  mac: ENC[AES256_GCM,data:DwZF8S6oNc5DKhLsLFXQPwXdeHKnYPYZnpvrczkrR9E//vom8MxDoXgkFhDXMJriBQE7PkfUMbyWzF6yCYVladnSJR3sk360JwOccw+8Cx0crr5hw/Qi2Ot1MWHpPLa9sG7eAd3ZdtfXbBqaf8YNgeHfxyyfK+m1KERsQ/d5bkg=,iv:ryyx5kMZuDKbH1iPSSkMxp+mT/ZLbg46BtZTktTJFg4=,tag:cdHdu0sF7Np2huGVBqzVxw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
