apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:3CzSzJXs0czglJXdZ+31whnPnY0uW74Citjqz22pmTiroK4cJyBrR2L8TYzaqLcOFXpuQ5KKUDYSNeGIJg0cvBsO37IjiytrjUYURAY2Trr0AyAvDAyoGNYsU2wmKx4LlfGa/oQDpuvdHsOAMreP0qpAq0ZYlQkKm+H15dHDus8znR/Zf9VAOo7H1oyx+kRcqPxGZwq6SJo8zibqR4NV71Ha/p1yunFGLAaAunljIDm4/ofn,iv:mEtuwaY5IwIpK5ZN36333MIceMjrNFUwkYTWFJ7jdHo=,tag:a0Cqbg69+l+qAVpkQOoIoQ==,type:str]
sops:
  age:
    - recipient: age1k77zxd34j3sl930pyrscjchegnugy6pgea6vpscwn3wt8kkf7u2sm6vykc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0T1lEakxodXpOemkwc09i
        aTF4Zjczdk85WlQrK0dacHNJeFpQVld3UHdVCmhIVGVOUjc0ZTZlRFA2ZWpWQi9s
        cmNhK2J3UWt5dHZuRUIyY2RyWjlxWlUKLS0tICtkODFOTnpqTTNEUkpZVEFTSnBY
        dUUyU2RUTVNtaFA0NitVWmZ1Z0I0TzgKrpDZl1/AKdQN8T+fqemrOhN8zmmOW9lt
        btUfQdaiuWsEWJtP+ZAI3RVUFxyTBT9SQlhO54qeCMGvl1QF2ApZQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T14:14:50Z"
  mac: ENC[AES256_GCM,data:6bvQs+1PTbL7/+iCI7xoxn3dAXvBLOAKj/y0Bcie8efeVun4gUUwEYGoVurT9MKJpCXJhcUsuXzhlWDuNoyx88OKvj8rFlKe7AYqYnCGxocauAl0EZeV5E+N13163JMfHA8Jb36n8hScUUCHmexoKPNKSC1dZSIf7FGjn050hzQ=,iv:x9kAeIq6yJnhOJLHZe9KomNZrkev7zLtpiT1l8XUdTU=,tag:PzkDetukWiN6rPJNpD68Ow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
