apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:+Q0YQL1mJPuXa1vF8Lu0NwcHhVZllyK/jWtNtZ/iAI0zm1eX60Q8Le8ufuqymXP3Ye7MIfphgre64DjIZRgxV+A+E7vYqZCJznEVTZY+QSY68Xw/swiBr/beUDKRWymibFl90pzsp1bZKtod1D455EMyjapwKyBkM0oBTuAedBiLesjqYLbxJXpBCSbxe5RBf0LuzKNl1gRcRVyf6JdJ5vSXHWzgMvbMkS0UcJaj1T/S1Sy/,iv:mUAaqbvwzg/yyHEPPG1zyPrbav2NWbBCZ+0qDPERJjE=,tag:iqVl8tZUSpwiPznHBPNglg==,type:str]
sops:
  age:
    - recipient: age1k77zxd34j3sl930pyrscjchegnugy6pgea6vpscwn3wt8kkf7u2sm6vykc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYVA2L21LdWVDU0NPQVZG
        dlJyek16KzVpVEltR21jYUp1dzc4RjNTMjJvClB2NWdsdEs3U1lNOGQvbVB1dldD
        WEU4VjhTd0I0RVlpQit0Uk9GSmR6K2cKLS0tIEtYRTg1djZpQ3U2NGwwNURzQlBO
        Z21WRmw5Y1NmTVNtM0wrZ1Z4ZzVaaTQKkNXc42LooEdHjf0dTgoPRgW25ALCNS7n
        ZKOgIsOvJOxel4jZpdFJkDwoCLM2EJrYTWb0g2B1W4s38RAuXDyZiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T12:56:31Z"
  mac: ENC[AES256_GCM,data:1Kbkn6Js8F6YbWaqqfoyz5lWa10JLSRLQBkn31rBiq6YDnMrCv9xMSorvLXIcC+DGF2OOrqDLLVWMc/0hGBMwsve0GfPQGDl3GYz+JGa24l5zH7zi/cDAzDixHntFcemdHbFH43i5VzdUK9pqOTmwL2tDebRY1uE6nGonqYpjrU=,iv:FZxx2AJ/45+jvHwaE3m6J27oF1H2pEz6qlrzSTFhJfQ=,tag:5itm4T6Frmbaq50k/Io51Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
