apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:jxTiLM8SrYIlyxWGzusTB0ZH4KE6q5Li8g2QSTR4VC+Tn9phJ3r+6He+gnXzPJ+j90I8WXgSz+rEoOTg3841RSrO7idlrQE2v5faEx58FrZaJ5+aXZn/LPXQ0M+kf75LGQYf3rC5TOdyWPZy+EYA22qZxbgY3Uks+U3dcaDRgv+Ca4wAR86yZRZme/UOel0GEuJ4AcyNR4+NT3yTABC3KCYtttvrd0LwGcNBGLoa8WTF0sW0,iv:6zNCSQJPKQj0k9NlkrQ/SYpXjY7LNZJndx/8I2WSmQk=,tag:RaxlX51ixEzPhXNmGHp65g==,type:str]
sops:
  age:
    - recipient: age1k77zxd34j3sl930pyrscjchegnugy6pgea6vpscwn3wt8kkf7u2sm6vykc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZmg3d0gxRkJ3bWhaaTFv
        ZjVQcFlTRUgxK2l0bjdBd29MU3MrQmgvQ1FjCkxwT05FOXRoWllZTXlQMk5za1p5
        SXI2ZWROUm9nZnNYSElZQlFHcVVCRmcKLS0tIC9YVGxXSk1DMTI2cUtFYUI2UTB3
        YlRIMXZnMEJmd2FObXRWQXFZMGhiY1EKaAByVE8446zQZ8WqUDlF5FO7nVqgxgtt
        3wt0Au2/W7hWBW/v5PHqSgK4vK6fAxyHB1wvT14ZeRy8uaWyMF0hkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T17:50:31Z"
  mac: ENC[AES256_GCM,data:3EkHi0PYPrmpSIdc++dT8mO+iChI3/9VWztU+yaD5zEkzX7u6xPUFoVrxNNmBMXygJZPzjmxkBxPX/PHyvvZdXr1zzGyPptO5jTGG/fLJxd6iZkJNMROsg15gTeF+eBle2x3pEAvyYSeQAxvZXDH5QpgWU/FSoDBqVD52Tl+vIM=,iv:/SQB0rMLO0ncVOMMZiER6mnoMiTwgi+NeH+yutU2l5I=,tag:FUqc1KT7DpyBaiIYLfqSvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
