apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:U/c0lqxPx0Y0rl5Y65xAIncJVFnGo8g5J6rTkTHaEolYItpLFRAwug==,iv:rbjCGg3MVIzONBE78Kj5KZPWRl+FkAi8MbzaIXEwXFc=,tag:8ZFUGPUUsCOKfuBfrPdDMA==,type:str]
sops:
  age:
    - recipient: age1k77zxd34j3sl930pyrscjchegnugy6pgea6vpscwn3wt8kkf7u2sm6vykc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUFFMQTdzU09lMVhEVkh5
        MDE1L2xHUDU2Q04vYi9MYzljTDZLT2s5NkJjCk16dWdMOWUxcTROUjhFbi9UckpB
        NGdORXRJd1p5ZWRORnFlLzZmQkJ6VU0KLS0tIFcyR3dUQWNGTWw3amttUzVxbHVm
        cHJzamkrQ09ua1BhdEt4WUZUWTdDcmcKwaEmh+2Ono2ySm+4/njGT0thwaANx/0r
        RLaDyB4TIsXitvS3hLggD020XcUHqw0sHKOm40V0zE6g7PPi3fOFZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T12:56:31Z"
  mac: ENC[AES256_GCM,data:fI5ze28y8HNZh/7bE/ftrB8KyvaM7HxneTEa8AAuOv698sF3O/1nG/fimxqTy3zOrBvc6n8ndQpT087Dq4XZcXWU1IG5qR9Pe2USPUtgjDEURdZIiHpCWXM1HkMBDDIzPQ2pcVmPB9mSoe0ldJkWbGiop23R8ZCSPH771PA3m/Y=,iv:x8BcjeTpf/J3Woq+EVAyf4XYKXYHWUUVDZyf9IK+/e0=,tag:+xIQ43/sdWFNUGA1zDeNjQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
