apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:niBa3my6JbAdeKYsuh12+mJr0k0zuUJQ7e8ct3F8a9rGtoLzbbmbfg==,iv:KU3KmV7GoPYZax5GyJ75c2ZoQSAj5mNpL/PRdY+LiFk=,tag:vV4zcsif4WncIHoUmx2Abw==,type:str]
sops:
  age:
    - recipient: age1k77zxd34j3sl930pyrscjchegnugy6pgea6vpscwn3wt8kkf7u2sm6vykc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeDd3WC9SbU9XL2pBc3kv
        OC9mUDh6TUthMkw0WHBaQlhIR2JMdHlLaUFrCktxK2g3c1V4S0F4ZVlnbk1nU1FE
        OVR2WW1vTW5XS2M1Y0did2U5Y2dMZjgKLS0tIDVnRDFLQWlNWWxNRWRMWU9ybVVT
        QVVIT3pjWmo1cmlIZUxKMGxxR1F2RjQK6wkZ471Zq+/bVAFQVNVTIDeGQ0IwFrmu
        BHw0FLd7fbkMHhifzvYAo+gZK7IPTlw+RM06TxnFv+5OBnJ1D4AvJw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T14:14:50Z"
  mac: ENC[AES256_GCM,data:jaUxcHd2YzITvdafBY1/MCnk3o1nUxYIoeNmta1WYDMv1GaybGjdaYxw7rjYh0+nYqHaa82W1kCc58zmfYuG1kDuvIM7ODEswej9EOe66P89Ac7owQxPkUk3bWlDE1YIxOyBeOOR/M7R542bigfO1kEA1XzcSfNryqOPQXxpL/w=,iv:15VBcvaL+ghUrJHJX7qAyTPfzk686In+itD14ToUALY=,tag:L3rdAAcRUwBIPjvJjEf8ug==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
