apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:66of1tnjM4oMWvxQRv7fOTtCdCEbXHTKiy1S7OCZHix8B1UsjtPVWw==,iv:R34Dt9HF3KNQVNmQVQZeOCjkb0+sQSrDi7OstYi6pD4=,tag:w7EQnt6sO4eAymI6ZTe1rg==,type:str]
sops:
  age:
    - recipient: age1k77zxd34j3sl930pyrscjchegnugy6pgea6vpscwn3wt8kkf7u2sm6vykc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVM3d0MzEyS1ZaZUQrSjEy
        ZWdXb2dma01MTHVIU3dFTEQzaHExMG9FcjJ3Cm5wcExBWDkrR1hnN2JJa2l3VzFt
        V0VlYi9iVWRhWmtQU0NRdXVWN1hhNjgKLS0tIEVOMFFwNmJBZ2ZZaUFQcDZyeUhv
        NkZMTXFHNnFnci9SNTlJR1RZNjAwUXMK+dkoC9vTTu+eiLTuLWNNUmr9wniKsRhO
        MApTP1zn/Mp0btwvLK+LvMURmJz9o6+w0/SLrn8z1Us3WNnWav3sLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T17:50:31Z"
  mac: ENC[AES256_GCM,data:tLMvi3Gf9LvwjYofPRROI+k1P95AG5iRKcjrdEzImsZaHsd/FW0IbeNfNd849iN3d9lwtJsEzvDi+rGSIhHfWNcRO0lW/Z8sUGjmtXFZl0fLCTUX1caZi2jwt1PxxPdCBOyqQ8m2QETU87deq3ZVLKJqz8U8hdqyppYSfV0FWV4=,iv:qpJ+EQP1XVxrmiq/+FmBFQW1dRNpY5prVKau8vck/Ys=,tag:yL81I8MZatNm0iRGY/YMGQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
