apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:g6dzVMQBF8J2NsB3dqYcGAKwTQj01+ORJ9euD8fbaxpw9rWmrXQC+A==,iv:AwF3n1glZb9W0N/pMU5MmpB7B7HKht3uujhKxo1NbH0=,tag:UEPC5tvlSXnxc+Tb7c8ktw==,type:str]
sops:
  age:
    - recipient: age1k77zxd34j3sl930pyrscjchegnugy6pgea6vpscwn3wt8kkf7u2sm6vykc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDOWRaNm9aaVdhOW9aT2NY
        NkYvV1NqMlg5bzdDdk1iK0RpMS9Yc2NReGx3CnhHUDErTUxFdzVoWmFCaHZ6QWlH
        YVhxVmNOWFYvNVVrOTFFeHZpWlFySzAKLS0tIFFkdmpLU3F5T3hIWFF2cHFpQkZw
        ZERxeVErQkJqR01MeWZ4cDRnMkNzY2sK7P6B/GNO5dpbbXka94RP2d6A6nWr/9Iz
        xI5/S24GrXxIfOWjKxi4dBeZs5hFAlH69xJmaOrDMlA8A9wUy+8JSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T18:36:08Z"
  mac: ENC[AES256_GCM,data:C5lFtYPejci6W/ZCJz1qvDoiIRVNE5XtPZjNFdAqkXMvN3jHBF8CpnX+3pMsqYQPsR8CyuzlhXooEEctRvzTzggvRk3j9lojQiYc+bBDmbzjIeX+AVA27ihOGNGEXs5Ik6TYpYlbNCV9E4/wzXXmfxNeZIRMGagqHl+371Nke5M=,iv:ATr+UkDqty7TaKqqpC2a2ZiBWDFYQR5VS5RMVVtViXI=,tag:2HrZwX8HLaKAV5f84GOWdQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
