---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: longhorn-internal
  namespace: longhorn-system
spec:
  parentRefs:
    - name: internal
      namespace: longhorn-system
  tls:
      sectionName: https
  hostnames:
    - longhorn.home-ops.dev.nxyzo.com
  rules:
    - backendRefs:
        - name: longhorn-frontend
          namespace: longhorn-system
          port: 80