apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-s3
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:R/HDffIUbb8/PTk3YYFQq3MQj0E=,iv:CpksnxxGwxscA+K4UwWAgOMhjuKwing5WlZTa7y82No=,tag:USH9g+HLoTJCU/m9GPMZHQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:hIWApiVqi2iwBSew1U4MhKc2DicBTF25nKG1dydQ969pKWR/DRP2eCs=,iv:h8awwIKD9t23HyrC/3ZXoEbRwtlMyxHC0kDyTrrwsrI=,tag:96W/1yB7QLVacBDYypeoFg==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:mNb6/uvw1Z7ScwmyUkNjTsYeKMX3D77aTyKkdxS1+iIpalY=,iv:c5KCtyfuNCallhpEdUjqVP9DfwTJh9JGn60HDxN88Jw=,tag:CJcS7qLP6N9qO0OWJEeYRg==,type:str]
  VIRTUAL_HOSTED_STYLE: ENC[AES256_GCM,data:07DBZA==,iv:QMaKme2sSNY8Go0xjE+J34KV3x1f8BleyxUSV1LXSAE=,tag:ofUwHCY+d49upX+Q0BneJQ==,type:str]
sops:
  age:
    - recipient: age1k77zxd34j3sl930pyrscjchegnugy6pgea6vpscwn3wt8kkf7u2sm6vykc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArM1NQZUsreStpcjdVdGlw
        UXBWRmRWRkZCbXd0ZnMvTUtSdWRxUURNSUV3CitXY1d4SWt5MXphdUpDOE9sdDYz
        MWFVbVkyWTE4NnpyU0NLd3dub3pYYXcKLS0tIFpNVWx3aEZLQ1V4NXVjNWRjQVJX
        VmxnWFBJSi9OUndzZFRhMFovY1BRQ0kKmIhtQpkc9KC+IIVPbKGtdgfXqmVcAuED
        vhSALHPhwtmQV7fIiN4ajGEVcht0kJRASfUWh2sPKGrmKLynT6Us7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T21:26:54Z"
  mac: ENC[AES256_GCM,data:e/HnAMi4FxHVLYVhRv7hqbBrM/laHEw/wbEWox+jopC1RnfxkkuI1hdxgBl4NaK4X+ioCeVGYzcZTHaKePUfgUKRohIN5a7sOxUWBb9fBwKPOVbfPem9xZdXzYaWP5+EjahqUVlyjsQ4iS14YoOibiSpHcp5F9HbQ6fMLgbbubg=,iv:K+fstiyvjcpqu7SrzEiIZF6VVYSEJPWlNQxnRHc7jFQ=,tag:+z9+lZd6E/lMZWgQLR8Uwg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
