apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-s3
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/3IYb0nJxip8Q3Dip0dKfoS8zRk=,iv:xX9XKdFtIBLYxNX4POjaV1JEEJW2B+e5LL1LscT37JA=,tag:dcG5Stfo9OiQm5ejZ9kbng==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:WRhDETo3n1jgJCMvxMJke+XX7hGqKMN57rVIHToMlSC4EiAPWs8rMA==,iv:WxXjNErfpoaF26gNhMbUPcLgrrO8FnzjoSFQCTWRB0w=,tag:wv5zrD1yvNSauzcjS9YwMQ==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:U81Q6wmr9vUUSl7GHj05750Ea+pMlBLXiyJYaASfkII8FQ==,iv:6tYf+CSig7lssPpuCbXfOY4YfnXl4kraIHyvsTvwiik=,tag:1lkzJ09m3w7zpzetBgkR1Q==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:4NNYe0xNcxYJ,iv:VytL8WsKfTTxlpbF/fKMDH3YlshHPRq/N+0Vqsw9Ci0=,tag:lmZSisdghDSNVSfW1rxlCg==,type:str]
sops:
  age:
    - recipient: age1k77zxd34j3sl930pyrscjchegnugy6pgea6vpscwn3wt8kkf7u2sm6vykc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArM1NQZUsreStpcjdVdGlw
        UXBWRmRWRkZCbXd0ZnMvTUtSdWRxUURNSUV3CitXY1d4SWt5MXphdUpDOE9sdDYz
        MWFVbVkyWTE4NnpyU0NLd3dub3pYYXcKLS0tIFpNVWx3aEZLQ1V4NXVjNWRjQVJX
        VmxnWFBJSi9OUndzZFRhMFovY1BRQ0kKmIhtQpkc9KC+IIVPbKGtdgfXqmVcAuED
        vhSALHPhwtmQV7fIiN4ajGEVcht0kJRASfUWh2sPKGrmKLynT6Us7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T15:45:51Z"
  mac: ENC[AES256_GCM,data:pfBEVDPJWoAtzqpRvniFenH5o8bCs/rCCTagb2n4sMctrFIlqhFRD6vHC3X+7ZDhu4z4oIwhav4g/gB/8Z2lmPz3VtB+TvVrwbVjnAaBJjdfsC6pc+PADfuP1d6UyQhUypPdugYpotoYmncnL6Y74y1jze5Ms7z4AAcvPtpDvhU=,iv:DihyEyq+hGVX4H0ePOZxxhEQ7Ri2uHzYaRTUf5hC7Gw=,tag:r+LJkGVWOQdA8w9elXh/Hw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
