apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-s3
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:wRAebFlMNq+0LKeZFWW0bc5nO+SkakZHPWcKhTYCiUtiqY93FzFO5A==,iv:BvaO0MbXFHNw9Re4+mnrIciAYchj51QtGvOQ4jQ8iDs=,tag:H/mSpEpSEvVNEP739wMv5A==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:7xc353kpXHuxP0phTfVUlzjKl90=,iv:oa6nelLybykRmuiEnQ9cbkWR5Pw19Bb3eNy537modf8=,tag:lVQkzoSC2No3ltSwzIvkzw==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:GKyVSIM4TaCPYJS0wqo+zJkQfn3HyaFUk1lF,iv:QrdVkSUUs+5DGOSIwwqh9vb7RfhU3Xs4wW1I/xwp16I=,tag:BMERDN+LK2+1QmZsoguWnA==,type:str]
sops:
  age:
    - recipient: age1k77zxd34j3sl930pyrscjchegnugy6pgea6vpscwn3wt8kkf7u2sm6vykc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArM1NQZUsreStpcjdVdGlw
        UXBWRmRWRkZCbXd0ZnMvTUtSdWRxUURNSUV3CitXY1d4SWt5MXphdUpDOE9sdDYz
        MWFVbVkyWTE4NnpyU0NLd3dub3pYYXcKLS0tIFpNVWx3aEZLQ1V4NXVjNWRjQVJX
        VmxnWFBJSi9OUndzZFRhMFovY1BRQ0kKmIhtQpkc9KC+IIVPbKGtdgfXqmVcAuED
        vhSALHPhwtmQV7fIiN4ajGEVcht0kJRASfUWh2sPKGrmKLynT6Us7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T13:54:14Z"
  mac: ENC[AES256_GCM,data:eMtPXs8wJJe0t+BYekGTMdPQI/j5pCmzRFLR8qRjQHlCYOV4dmgmsSHm9uqsa/PLAxrcFfsU9WtEnstbZd+DTraea3emXseKZpMx0uTQP296pcDwulUemUOYTicS1Z8rM81HowS3pSzspC056lZSVWz7NZBhg0Er0aTRWvIX6o4=,iv:vBtzWWtr5+KD/2fBXWlg0G9DZrfWNXE31HQKTOQDp3c=,tag:e/4tNsHEi8Kctp+q5J5Lkw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
