apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-s3
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ROTeBF0w+TAoOoHa7yBcFx4zZwk=,iv:zq6xeHYfzPnFxTZxsvqu15xpH5YWPIioAiQt4ha1vuA=,tag:KtHjREGFKnPIo5mG1dvegg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:aKQDK77iMwBZ3JVR6SMe1QE9ap7aWsE5wU8MLKi8HLdAkc3fbjDjWjQ=,iv:OkjHU1PaYBQ0dSSsFxSz0r4zwSJJy6Bgusglm2uvMAc=,tag:Rbxi5Hegxo3QIKBcxJKwUA==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:dbFkLsmPBuaI59Iv9iMePt94BYkwzpHHjeQR4003Q8VEglE=,iv:t0ji1RgjwTy0bvTbhx7393Ldo4qzPeFTFYBReBkfUZQ=,tag:jmaRkT6axwEPxoreVHq09g==,type:str]
  VIRTUAL_HOSTED_STYLE: ENC[AES256_GCM,data:ewzrzQ==,iv:VJcMebZ/4G/5trbg5y4qbWx9XGiH6u2tch727qb6CUM=,tag:IluwoY82h/m8VrXXHw1KAQ==,type:str]
sops:
  age:
    - recipient: age1k77zxd34j3sl930pyrscjchegnugy6pgea6vpscwn3wt8kkf7u2sm6vykc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArM1NQZUsreStpcjdVdGlw
        UXBWRmRWRkZCbXd0ZnMvTUtSdWRxUURNSUV3CitXY1d4SWt5MXphdUpDOE9sdDYz
        MWFVbVkyWTE4NnpyU0NLd3dub3pYYXcKLS0tIFpNVWx3aEZLQ1V4NXVjNWRjQVJX
        VmxnWFBJSi9OUndzZFRhMFovY1BRQ0kKmIhtQpkc9KC+IIVPbKGtdgfXqmVcAuED
        vhSALHPhwtmQV7fIiN4ajGEVcht0kJRASfUWh2sPKGrmKLynT6Us7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T21:22:10Z"
  mac: ENC[AES256_GCM,data:HAgtj5GNoMznLhqIlckqH1Zru/O1wyp+JHmA7taYQcfS2lc0xCkz9YVe+GBvW+ji9cfwak3bRgHk4P5uj1wKJA9Ug44R6yZh9/Ta/x80d87sGO3T18XDGmjdde7dhdn3McP4xXqAyqWN9otYjUcKidCzgSwl4Sugg6jK4kJEppY=,iv:k5oQc1LE5HRuhkoA2dhEVf3SGuuRY0bxghH5gXRQhxM=,tag:7ZBT++8JZzbIrbrtm1x1lQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
