apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-s3
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:R/HDffIUbb8/PTk3YYFQq3MQj0E=,iv:CpksnxxGwxscA+K4UwWAgOMhjuKwing5WlZTa7y82No=,tag:USH9g+HLoTJCU/m9GPMZHQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:hIWApiVqi2iwBSew1U4MhKc2DicBTF25nKG1dydQ969pKWR/DRP2eCs=,iv:h8awwIKD9t23HyrC/3ZXoEbRwtlMyxHC0kDyTrrwsrI=,tag:96W/1yB7QLVacBDYypeoFg==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:mNb6/uvw1Z7ScwmyUkNjTsYeKMX3D77aTyKkdxS1+iIpalY=,iv:c5KCtyfuNCallhpEdUjqVP9DfwTJh9JGn60HDxN88Jw=,tag:CJcS7qLP6N9qO0OWJEeYRg==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:+fQVng==,iv:gBX/36qIzX9WdwQjvzz6l5HSjDf9A7FBQM94JRukfLk=,tag:usrHl1voC/tUqrL3SmcJdA==,type:str]
sops:
  age:
    - recipient: age1k77zxd34j3sl930pyrscjchegnugy6pgea6vpscwn3wt8kkf7u2sm6vykc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArM1NQZUsreStpcjdVdGlw
        UXBWRmRWRkZCbXd0ZnMvTUtSdWRxUURNSUV3CitXY1d4SWt5MXphdUpDOE9sdDYz
        MWFVbVkyWTE4NnpyU0NLd3dub3pYYXcKLS0tIFpNVWx3aEZLQ1V4NXVjNWRjQVJX
        VmxnWFBJSi9OUndzZFRhMFovY1BRQ0kKmIhtQpkc9KC+IIVPbKGtdgfXqmVcAuED
        vhSALHPhwtmQV7fIiN4ajGEVcht0kJRASfUWh2sPKGrmKLynT6Us7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T21:32:58Z"
  mac: ENC[AES256_GCM,data:lyUCw9Pca49ZzmI9Zcux+u56r0hsbxwW/1nZq3jsWpa0ROuCvI+h3R6H88kH4LQw/WpI0XnLK0ixxnARcJPIBBx7yCf1ay9LNvwP5PoLy2VN0wsYe8TaLFpoeIyFVSV7LjkN+yV2lk4BXLOsuGRPhhXZ0GvwHz1yB/+VGpfcFIc=,iv:UHCsWfrvaDylBB6DMfkUHhMTvG/yDfAr0mEYaniyK00=,tag:rKi0jR+GYvc/Iwv+lJrjVA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
