apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-s3
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:wRAebFlMNq+0LKeZFWW0bc5nO+SkakZHPWcKhTYCiUtiqY93FzFO5A==,iv:BvaO0MbXFHNw9Re4+mnrIciAYchj51QtGvOQ4jQ8iDs=,tag:H/mSpEpSEvVNEP739wMv5A==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:7xc353kpXHuxP0phTfVUlzjKl90=,iv:oa6nelLybykRmuiEnQ9cbkWR5Pw19Bb3eNy537modf8=,tag:lVQkzoSC2No3ltSwzIvkzw==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:uEd53dUyeDu0bq80B8qp4e0Fm5q9N6Y+LKWY7QC5NlHrFMk=,iv:q9qSopXHDRCEboFwxdY2bjfkK9dfqtqEIlNuZlppsQI=,tag:EE/GpgE+kNcoeVnn8Q40ag==,type:str]
sops:
  age:
    - recipient: age1k77zxd34j3sl930pyrscjchegnugy6pgea6vpscwn3wt8kkf7u2sm6vykc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArM1NQZUsreStpcjdVdGlw
        UXBWRmRWRkZCbXd0ZnMvTUtSdWRxUURNSUV3CitXY1d4SWt5MXphdUpDOE9sdDYz
        MWFVbVkyWTE4NnpyU0NLd3dub3pYYXcKLS0tIFpNVWx3aEZLQ1V4NXVjNWRjQVJX
        VmxnWFBJSi9OUndzZFRhMFovY1BRQ0kKmIhtQpkc9KC+IIVPbKGtdgfXqmVcAuED
        vhSALHPhwtmQV7fIiN4ajGEVcht0kJRASfUWh2sPKGrmKLynT6Us7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T20:52:59Z"
  mac: ENC[AES256_GCM,data:8xR6zh8Ywsd83o/Zky6klyOSA9WqE3/2Gp+tUqIpFQYlu/nW2jFsSlT1LQlCMHa/YQoSKzX9jwBpoz5GKKxiSmtKArdiOha17/WPqxVrn4DfT6XmGnZ7znTRRhvbaV16pqo96z6zKOjjWQgS8HVUH3tAVwVySL3oYyrGz03L9ns=,iv:aZbG1L3E0XxvJrLxWd1YglMtVg/OJ/7zsauEda72M5M=,tag:GlPVh9ZCLpW8vEtdyTB0FQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
